org: kostya717
app: learning
service: learning

provider:
  name: aws
  runtime: nodejs20.x
  environment:
    TOKEN: 11111
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:*
        - events:*
      Resource: "*"

functions:
  description:
    handler: services/description.description
    events:
      - http:
          path: /
          method: get
  get_posts:
    handler: services/posts/get_posts.get_posts
    events:
      - http:
          path: /posts
          method: get
  get_unique_post:
    handler: services/posts/get_unique_post.get_unique_post
    events:
      - http:
          path: /post/{title}
          method: get
  add_post:
    handler: services/posts/add_post.add_post
    events:
      - http:
          path: /add_post
          method: post
  edit_posts:
    handler: services/posts/edit_post.edit_posts
    events:
      - http:
          path: /edit_posts/{category}/{title}
          method: put
  delete_post:
    handler: services/posts/delete_post.delete_post
    events:
      - http:
          path: /delete_post/{category}/{title}
          method: delete
          authorizer: user_authorizer
  user_authorizer:
    handler: services/authorizer.user_authorizer
  new_post_event_listener:
    handler: services/event_listeners/new_post_listener.new_post_event_listener
    events:
      - eventBridge:
          pattern: 
            source:
                - "com.mycompany.category.new_post" 
            detail-type:
                - "post_created"
  get_posts_by_category:
    handler: services/posts/get_posts_by_category.get_posts_by_category
    events:
      - http:
          path: /posts/{category}
          method: get
  get_info_by_categories:
    handler: services/categories/get_info_by_categories.get_info_by_categories
    events:
      - http:
          path: /category_info
          method: get
  add_category:
    handler: services/categories/add_category.add_category
    events:
      - http:
          path: /add_category
          method: post
  delete_post_event_listener:
    handler: services/event_listeners/delete_post_listener.delete_post_event_listener
    events:
      - eventBridge:
          pattern: 
            source:
                - "com.mycompany.category.new_post" 
            detail-type:
                - "post_deleted"


resources:
  Resources:
    PostsWithCategories:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: posts_with_categories
        AttributeDefinitions:
          - AttributeName: category
            AttributeType: S
          - AttributeName: title
            AttributeType: S
        KeySchema:
          - AttributeName: category
            KeyType: HASH
          - AttributeName: title
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: GSI1
            KeySchema:
              - AttributeName: title
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
